export type EducationSystem = 'IGCSE' | 'American' | 'IB' | 'National' | 'University' | 'Projects';

export const EDUCATION_SYSTEMS: { id: EducationSystem; label: string; labelAr: string; emoji: string; description: string }[] = [
  { id: 'IGCSE',      label: 'IGCSE',                           labelAr: 'IGCSE',                          emoji: '🎓', description: 'Cambridge & Edexcel IGCSE / O-Level / A-Level' },
  { id: 'American',   label: 'American Diploma',                labelAr: 'الدبلوم الأمريكي',               emoji: '🇺🇸', description: 'SAT, AP Courses & American High School Diploma' },
  { id: 'IB',         label: 'IB (International Baccalaureate)',labelAr: 'البكالوريا الدولية (IB)',         emoji: '🌍', description: 'IB Diploma Programme (DP) & MYP subjects' },
  { id: 'National',   label: 'National Systems',                labelAr: 'المنهج الوطني',                  emoji: '📚', description: 'Egyptian, Saudi, UAE & other national curricula' },
  { id: 'University', label: 'University Subjects',             labelAr: 'مواد جامعية',                    emoji: '🏛️', description: 'Undergraduate courses — Math, Science, Business & more' },
  { id: 'Projects',   label: 'University Project Assistance',   labelAr: 'مساعدة في المشاريع الجامعية',   emoji: '💡', description: 'Graduation projects, research papers & academic writing' },
];

export interface Subject {
  id: string;
  name: string;
  emoji: string;
  tagline: string;
  description: string;
  topics: string[];
  sessions: number;
  gradient: string;
  glow: string;
  system: EducationSystem;
}

export type Level = 'OL' | 'AS' | 'A2' | 'AL';

export const LEVELS: Level[] = ['OL', 'AS', 'A2', 'AL'];

export const LEVEL_INFO: Record<Level, {
  label: string;
  difficulty: string;
  description: string;
  pill: string;
  bar: string;
  barWidth: string;
}> = {
  OL: {
    label: 'Ordinary Level',
    difficulty: 'Easy / Average',
    description: 'IGCSE foundation — core subject knowledge for all students.',
    pill: 'bg-blue-50 text-blue-600 border-blue-200',
    bar: 'from-blue-400 to-blue-600',
    barWidth: 'w-1/4',
  },
  AS: {
    label: 'Advanced Subsidiary',
    difficulty: 'Medium',
    description: 'First half of A Level — introduces advanced concepts and deeper analysis.',
    pill: 'bg-amber-50 text-amber-600 border-amber-200',
    bar: 'from-amber-400 to-amber-600',
    barWidth: 'w-2/4',
  },
  A2: {
    label: 'Second Year of A Level',
    difficulty: 'Hard',
    description: 'Second half of A Level — complex topics requiring strong AS foundations.',
    pill: 'bg-orange-50 text-orange-600 border-orange-200',
    bar: 'from-orange-400 to-orange-600',
    barWidth: 'w-3/4',
  },
  AL: {
    label: 'Full A Level',
    difficulty: 'Very Hard',
    description: 'Complete A Level combining AS + A2 — the highest qualification offered.',
    pill: 'bg-violet-50 text-violet-600 border-violet-200',
    bar: 'from-violet-500 to-violet-700',
    barWidth: 'w-full',
  },
};


export const subjects: Subject[] = [
  // ── IGCSE ──────────────────────────────────────────────────────────────────
  {
    id: 'mathematics',
    name: 'Maths',
    emoji: '∑',
    tagline: 'Numbers, patterns and exam strategy',
    description: 'Build rock-solid foundations in algebra, geometry, statistics and number theory. Our structured approach takes you from core concepts to A-Level mastery.',
    topics: ['Algebra & Equations', 'Geometry & Trigonometry', 'Statistics & Probability', 'Number Theory', 'Functions & Graphs'],
    sessions: 48,
    gradient: 'from-blue-600 to-indigo-700',
    glow: 'rgba(99,102,241,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'physics',
    name: 'Physics',
    emoji: '⚛',
    tagline: 'Forces, energy & the universe',
    description: 'Explore mechanics, waves, electricity and modern physics with hands-on problem-solving techniques that make abstract concepts click.',
    topics: ['Mechanics & Forces', 'Electricity & Magnetism', 'Waves & Light', 'Thermal Physics', 'Nuclear Physics'],
    sessions: 42,
    gradient: 'from-violet-600 to-purple-700',
    glow: 'rgba(139,92,246,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    emoji: '⚗',
    tagline: 'Matter, reactions & bonding',
    description: 'Demystify atomic structure, chemical bonding, stoichiometry and organic chemistry with clear explanations and exam-focused practice.',
    topics: ['Atomic Structure', 'Chemical Bonding', 'Stoichiometry', 'Organic Chemistry', 'Electrolysis'],
    sessions: 40,
    gradient: 'from-emerald-600 to-teal-700',
    glow: 'rgba(16,185,129,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'biology',
    name: 'Biology',
    emoji: '🧬',
    tagline: 'Life, cells & ecosystems',
    description: 'Study cells, genetics, human biology and ecology in an engaging way that turns complex biological processes into memorable knowledge.',
    topics: ['Cell Biology', 'Genetics & Inheritance', 'Human Physiology', 'Ecology', 'Biotechnology'],
    sessions: 38,
    gradient: 'from-green-600 to-emerald-700',
    glow: 'rgba(22,163,74,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'human-biology',
    name: 'Human Biology',
    emoji: '🫀',
    tagline: 'Body systems, health and physiology',
    description: 'Focus deeply on human anatomy and physiology with clear, exam-focused explanations and targeted revision plans.',
    topics: ['Cells and Tissues', 'Nutrition', 'Respiration', 'Circulation', 'Homeostasis'],
    sessions: 32,
    gradient: 'from-lime-600 to-green-700',
    glow: 'rgba(101,163,13,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'it',
    name: 'IT',
    emoji: '💻',
    tagline: 'Data, systems and digital tools',
    description: 'Master hardware, software, networking, data representation and programming concepts to ace both the theory and practical components.',
    topics: ['Data Representation', 'Computer Architecture', 'Networking', 'Algorithms', 'Databases'],
    sessions: 36,
    gradient: 'from-cyan-600 to-blue-700',
    glow: 'rgba(6,182,212,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'computer-science',
    name: 'CS',
    emoji: '🖥',
    tagline: 'Programming, algorithms and logic',
    description: 'Learn computational thinking, algorithm design and practical programming with full exam-board style practice.',
    topics: ['Problem Solving', 'Algorithms', 'Programming Concepts', 'Data Structures', 'Computer Systems'],
    sessions: 38,
    gradient: 'from-sky-600 to-indigo-700',
    glow: 'rgba(14,116,144,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'accounting',
    name: 'Accounting',
    emoji: '🧾',
    tagline: 'Books, statements and analysis',
    description: 'From double-entry to final accounts, we simplify accounting logic and build the skills needed for accurate exam answers.',
    topics: ['Double Entry', 'Ledger Accounts', 'Income Statement', 'Balance Sheet', 'Ratio Analysis'],
    sessions: 30,
    gradient: 'from-amber-500 to-orange-600',
    glow: 'rgba(245,158,11,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'business',
    name: 'Business Studies',
    emoji: '💼',
    tagline: 'Strategy, finance and enterprise',
    description: 'Explore business operations, marketing, HR and finance while developing the analytical and evaluative skills exam boards reward.',
    topics: ['Business Organisation', 'Marketing', 'Finance and Accounts', 'Human Resources', 'Operations Management'],
    sessions: 32,
    gradient: 'from-pink-600 to-rose-600',
    glow: 'rgba(219,39,119,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'economics',
    name: 'Economics',
    emoji: '📊',
    tagline: 'Markets, money and policy',
    description: 'Grasp micro and macro-economic principles with real-world examples, graph analysis and structured evaluation techniques.',
    topics: ['Supply and Demand', 'Market Structures', 'Macroeconomics', 'International Trade', 'Development Economics'],
    sessions: 34,
    gradient: 'from-yellow-500 to-amber-600',
    glow: 'rgba(234,179,8,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'combined-science',
    name: 'Combined Science',
    emoji: '🧪',
    tagline: 'Integrated biology, chemistry and physics',
    description: 'Get full support across the combined science syllabus with targeted practice in all three science disciplines.',
    topics: ['Core Biology', 'Core Chemistry', 'Core Physics', 'Practical Skills', 'Exam Strategy'],
    sessions: 28,
    gradient: 'from-emerald-600 to-cyan-700',
    glow: 'rgba(16,185,129,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'arabic',
    name: 'Arabic',
    emoji: '🌙',
    tagline: 'Language, literature and expression',
    description: 'Strengthen reading comprehension, written expression, grammar and literary analysis for First & Second Language IGCSE Arabic.',
    topics: ['Reading Comprehension', 'Grammar & Syntax', 'Essay Writing', 'Literature Analysis', 'Oral Practice'],
    sessions: 26,
    gradient: 'from-indigo-600 to-violet-700',
    glow: 'rgba(99,102,241,0.35)',
    system: 'IGCSE',
  },
  {
    id: 'national-arabic',
    name: 'National Arabic (Yr 12)',
    emoji: '📝',
    tagline: 'Year 12 focused Arabic preparation',
    description: 'Specialized support for Year 12 National Arabic with focused exam preparation and structured writing drills.',
    topics: ['Advanced Grammar', 'Model Essays', 'Reading Analysis', 'Exam Technique', 'Past Paper Practice'],
    sessions: 24,
    gradient: 'from-purple-600 to-fuchsia-700',
    glow: 'rgba(168,85,247,0.35)',
    system: 'IGCSE',
  },

  // ── American Diploma ────────────────────────────────────────────────────────
  {
    id: 'am-mathematics',
    name: 'Math (Algebra / Pre-Calc / Calculus)',
    emoji: '∑',
    tagline: 'SAT Math, AP Calculus & Pre-Calculus',
    description: 'Targeted prep for SAT Math, AP Calculus AB/BC and Pre-Calculus with practice-led sessions aligned to American curriculum standards.',
    topics: ['SAT Math Strategy', 'Algebra II', 'Pre-Calculus', 'AP Calculus AB', 'AP Calculus BC'],
    sessions: 40,
    gradient: 'from-blue-600 to-indigo-700',
    glow: 'rgba(99,102,241,0.35)',
    system: 'American',
  },
  {
    id: 'am-physics',
    name: 'Physics (AP)',
    emoji: '⚛',
    tagline: 'AP Physics 1, 2 & C',
    description: 'In-depth AP Physics prep with mechanics, electromagnetism and fluid dynamics, plus full-length practice exams.',
    topics: ['Mechanics', 'Electricity', 'Waves', 'AP Physics 1', 'AP Physics C'],
    sessions: 36,
    gradient: 'from-violet-600 to-purple-700',
    glow: 'rgba(139,92,246,0.35)',
    system: 'American',
  },
  {
    id: 'am-chemistry',
    name: 'Chemistry (AP)',
    emoji: '⚗',
    tagline: 'AP Chemistry — bonds to lab reports',
    description: 'AP Chemistry mastery: atomic theory, kinetics, equilibrium and electrochemistry with exam-style FRQs and MCQs.',
    topics: ['Atomic Structure', 'Bonding', 'Kinetics', 'Equilibrium', 'Electrochemistry'],
    sessions: 36,
    gradient: 'from-emerald-600 to-teal-700',
    glow: 'rgba(16,185,129,0.35)',
    system: 'American',
  },
  {
    id: 'am-biology',
    name: 'Biology (AP)',
    emoji: '🧬',
    tagline: 'AP Biology — cells to ecosystems',
    description: 'Complete AP Biology preparation covering evolution, ecology, cellular processes and genetics with structured FRQ practice.',
    topics: ['Cell Biology', 'Genetics', 'Evolution', 'Ecology', 'Molecular Biology'],
    sessions: 34,
    gradient: 'from-green-600 to-emerald-700',
    glow: 'rgba(22,163,74,0.35)',
    system: 'American',
  },
  {
    id: 'am-economics',
    name: 'Economics (AP Micro / Macro)',
    emoji: '📊',
    tagline: 'AP Micro & Macro Economics',
    description: 'Master supply, demand, market structures and macroeconomic policies for AP Micro and AP Macro exams.',
    topics: ['Supply & Demand', 'Market Structures', 'Fiscal Policy', 'Monetary Policy', 'International Trade'],
    sessions: 30,
    gradient: 'from-yellow-500 to-amber-600',
    glow: 'rgba(234,179,8,0.35)',
    system: 'American',
  },
  {
    id: 'am-cs',
    name: 'Computer Science (AP)',
    emoji: '💻',
    tagline: 'AP Computer Science A & Principles',
    description: 'Java programming, algorithms and data structures for AP CS A, plus digital concepts for AP CS Principles.',
    topics: ['Java Programming', 'OOP', 'Algorithms', 'Data Structures', 'AP CS Principles'],
    sessions: 34,
    gradient: 'from-sky-600 to-indigo-700',
    glow: 'rgba(14,116,144,0.35)',
    system: 'American',
  },
  {
    id: 'am-sat',
    name: 'SAT Prep',
    emoji: '📋',
    tagline: 'Math + Reading & Writing strategy',
    description: 'Targeted SAT preparation with timed practice, score analysis and strategy for both Math and Evidence-Based Reading & Writing sections.',
    topics: ['SAT Math', 'Reading Comprehension', 'Writing & Language', 'Time Management', 'Practice Tests'],
    sessions: 24,
    gradient: 'from-orange-500 to-red-600',
    glow: 'rgba(249,115,22,0.35)',
    system: 'American',
  },

  // ── IB ──────────────────────────────────────────────────────────────────────
  {
    id: 'ib-mathematics',
    name: 'IB Mathematics (AA / AI)',
    emoji: '∑',
    tagline: 'Analysis & Approaches or Applications',
    description: 'SL and HL support for IB Maths AA and AI. Focus on Internal Assessment, exam technique and topic mastery.',
    topics: ['Functions', 'Calculus', 'Statistics', 'Internal Assessment', 'Paper 3 Extension'],
    sessions: 44,
    gradient: 'from-blue-600 to-indigo-700',
    glow: 'rgba(99,102,241,0.35)',
    system: 'IB',
  },
  {
    id: 'ib-physics',
    name: 'IB Physics (SL / HL)',
    emoji: '⚛',
    tagline: 'Forces, waves and the quantum world',
    description: 'Comprehensive IB Physics support across all core and HL topics with IA guidance and past-paper drilling.',
    topics: ['Mechanics', 'Thermal Physics', 'Waves', 'Electricity', 'Quantum Physics'],
    sessions: 40,
    gradient: 'from-violet-600 to-purple-700',
    glow: 'rgba(139,92,246,0.35)',
    system: 'IB',
  },
  {
    id: 'ib-chemistry',
    name: 'IB Chemistry (SL / HL)',
    emoji: '⚗',
    tagline: 'Stoichiometry to organic chemistry',
    description: 'SL and HL IB Chemistry with structured revision of all topics, IA support and exam strategy for Paper 1/2/3.',
    topics: ['Stoichiometry', 'Bonding', 'Energetics', 'Organic Chemistry', 'Option Topics'],
    sessions: 38,
    gradient: 'from-emerald-600 to-teal-700',
    glow: 'rgba(16,185,129,0.35)',
    system: 'IB',
  },
  {
    id: 'ib-biology',
    name: 'IB Biology (SL / HL)',
    emoji: '🧬',
    tagline: 'Cells, evolution and ecology',
    description: 'Deep IB Biology support covering all core topics, Options and Internal Assessment design from start to finish.',
    topics: ['Cell Biology', 'Molecular Biology', 'Genetics', 'Ecology', 'Option Topics'],
    sessions: 36,
    gradient: 'from-green-600 to-emerald-700',
    glow: 'rgba(22,163,74,0.35)',
    system: 'IB',
  },
  {
    id: 'ib-economics',
    name: 'IB Economics (SL / HL)',
    emoji: '📊',
    tagline: 'Micro, macro and global trade',
    description: 'Structured IB Economics support with diagrams, commentary writing, IA guidance and exam technique.',
    topics: ['Microeconomics', 'Macroeconomics', 'International Trade', 'Development', 'IA Portfolio'],
    sessions: 32,
    gradient: 'from-yellow-500 to-amber-600',
    glow: 'rgba(234,179,8,0.35)',
    system: 'IB',
  },
  {
    id: 'ib-business',
    name: 'IB Business Management (SL / HL)',
    emoji: '💼',
    tagline: 'Strategy, HR and decision-making',
    description: 'Full IB Business Management support including case studies, HL extensions and IA research report guidance.',
    topics: ['Business Organisation', 'Human Resources', 'Finance', 'Marketing', 'Operations'],
    sessions: 30,
    gradient: 'from-pink-600 to-rose-600',
    glow: 'rgba(219,39,119,0.35)',
    system: 'IB',
  },

  // ── National Systems ────────────────────────────────────────────────────────
  {
    id: 'nat-mathematics',
    name: 'Maths (National)',
    emoji: '∑',
    tagline: 'Egyptian / Saudi / UAE national curriculum',
    description: 'Curriculum-aligned maths support for national exam boards including Egyptian Thanaweyya Amma, Saudi and UAE national systems.',
    topics: ['Algebra', 'Geometry', 'Trigonometry', 'Statistics', 'Calculus'],
    sessions: 36,
    gradient: 'from-blue-600 to-indigo-700',
    glow: 'rgba(99,102,241,0.35)',
    system: 'National',
  },
  {
    id: 'nat-science',
    name: 'Science (National)',
    emoji: '🔬',
    tagline: 'Physics, chemistry & biology (national)',
    description: 'Comprehensive national science support across all three disciplines for national exam preparation.',
    topics: ['Physics Basics', 'Chemistry Basics', 'Biology Basics', 'Practical Skills', 'Exam Prep'],
    sessions: 32,
    gradient: 'from-emerald-600 to-teal-700',
    glow: 'rgba(16,185,129,0.35)',
    system: 'National',
  },
  {
    id: 'nat-arabic',
    name: 'Arabic (National)',
    emoji: '📝',
    tagline: 'Grammar, writing and literature',
    description: 'Focused support for national Arabic curriculum — grammar, essays, literature analysis and exam preparation.',
    topics: ['Advanced Grammar', 'Essay Writing', 'Literature', 'Comprehension', 'Exam Technique'],
    sessions: 28,
    gradient: 'from-purple-600 to-fuchsia-700',
    glow: 'rgba(168,85,247,0.35)',
    system: 'National',
  },
  {
    id: 'nat-english',
    name: 'English (National)',
    emoji: '🇬🇧',
    tagline: 'English language for national exams',
    description: 'Grammar, reading comprehension and writing skills aligned to national English curriculum requirements.',
    topics: ['Grammar', 'Reading', 'Writing', 'Vocabulary', 'Exam Skills'],
    sessions: 26,
    gradient: 'from-sky-600 to-blue-700',
    glow: 'rgba(14,116,144,0.35)',
    system: 'National',
  },

  // ── University Subjects ─────────────────────────────────────────────────────
  {
    id: 'uni-calculus',
    name: 'Calculus (University)',
    emoji: '∫',
    tagline: 'Single & multivariable calculus',
    description: 'University-level calculus support: limits, derivatives, integrals, series and multivariable calculus with problem-solving focus.',
    topics: ['Limits & Continuity', 'Differentiation', 'Integration', 'Series', 'Multivariable Calculus'],
    sessions: 40,
    gradient: 'from-blue-600 to-indigo-700',
    glow: 'rgba(99,102,241,0.35)',
    system: 'University',
  },
  {
    id: 'uni-physics',
    name: 'Physics (University)',
    emoji: '⚛',
    tagline: 'Mechanics, thermodynamics & electromagnetism',
    description: 'University physics support for first and second year students covering classical mechanics, thermodynamics and electromagnetism.',
    topics: ['Classical Mechanics', 'Thermodynamics', 'Electromagnetism', 'Optics', 'Quantum Intro'],
    sessions: 38,
    gradient: 'from-violet-600 to-purple-700',
    glow: 'rgba(139,92,246,0.35)',
    system: 'University',
  },
  {
    id: 'uni-chemistry',
    name: 'Chemistry (University)',
    emoji: '⚗',
    tagline: 'General & organic chemistry',
    description: 'First and second year university chemistry: general chemistry, organic mechanisms and analytical methods.',
    topics: ['General Chemistry', 'Organic Chemistry', 'Analytical Chemistry', 'Thermochemistry', 'Lab Reports'],
    sessions: 36,
    gradient: 'from-emerald-600 to-teal-700',
    glow: 'rgba(16,185,129,0.35)',
    system: 'University',
  },
  {
    id: 'uni-statistics',
    name: 'Statistics & Probability',
    emoji: '📈',
    tagline: 'Data, inference and distributions',
    description: 'University statistics covering probability theory, distributions, hypothesis testing and regression analysis.',
    topics: ['Probability Theory', 'Distributions', 'Hypothesis Testing', 'Regression', 'Data Analysis'],
    sessions: 34,
    gradient: 'from-cyan-600 to-blue-700',
    glow: 'rgba(6,182,212,0.35)',
    system: 'University',
  },
  {
    id: 'uni-economics',
    name: 'Economics (University)',
    emoji: '📊',
    tagline: 'Micro & macro economic theory',
    description: 'University-level economics: microeconomic theory, macroeconomics, econometrics and policy analysis.',
    topics: ['Microeconomic Theory', 'Macroeconomics', 'Game Theory', 'Econometrics', 'Policy Analysis'],
    sessions: 32,
    gradient: 'from-yellow-500 to-amber-600',
    glow: 'rgba(234,179,8,0.35)',
    system: 'University',
  },
  {
    id: 'uni-cs',
    name: 'Computer Science (University)',
    emoji: '🖥',
    tagline: 'Data structures, algorithms & OOP',
    description: 'Support for university CS courses: data structures, algorithms, OOP, databases and systems programming.',
    topics: ['Data Structures', 'Algorithms', 'OOP', 'Databases', 'Operating Systems'],
    sessions: 36,
    gradient: 'from-sky-600 to-indigo-700',
    glow: 'rgba(14,116,144,0.35)',
    system: 'University',
  },
  {
    id: 'uni-business',
    name: 'Business & Management (University)',
    emoji: '💼',
    tagline: 'Management, marketing & finance',
    description: 'University business studies: management theory, marketing, financial accounting and organizational behaviour.',
    topics: ['Management Theory', 'Marketing', 'Financial Accounting', 'Organizational Behaviour', 'Strategy'],
    sessions: 30,
    gradient: 'from-pink-600 to-rose-600',
    glow: 'rgba(219,39,119,0.35)',
    system: 'University',
  },

  // ── University Projects ─────────────────────────────────────────────────────
  {
    id: 'proj-research',
    name: 'Research Paper Assistance',
    emoji: '📄',
    tagline: 'Structure, citations and writing',
    description: 'Expert guidance for writing research papers: topic selection, outline structuring, literature review and APA/Harvard citations.',
    topics: ['Topic Selection', 'Literature Review', 'Research Methodology', 'Academic Writing', 'Citation Styles'],
    sessions: 12,
    gradient: 'from-orange-500 to-red-600',
    glow: 'rgba(249,115,22,0.35)',
    system: 'Projects',
  },
  {
    id: 'proj-graduation',
    name: 'Graduation Project Support',
    emoji: '🎓',
    tagline: 'Planning, development and presentation',
    description: 'End-to-end support for graduation projects including planning, technical development, documentation and final presentation.',
    topics: ['Project Planning', 'Technical Development', 'Documentation', 'Presentation Skills', 'Defense Prep'],
    sessions: 20,
    gradient: 'from-amber-500 to-orange-600',
    glow: 'rgba(245,158,11,0.35)',
    system: 'Projects',
  },
  {
    id: 'proj-programming',
    name: 'Programming Project Help',
    emoji: '💡',
    tagline: 'Code, debug and deliver',
    description: 'Hands-on help with university programming assignments and projects across multiple languages and frameworks.',
    topics: ['Project Design', 'Coding Guidance', 'Debugging', 'Documentation', 'Best Practices'],
    sessions: 16,
    gradient: 'from-sky-600 to-blue-700',
    glow: 'rgba(14,116,144,0.35)',
    system: 'Projects',
  },
];
